language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - vendor/
    - tools/

stages:
  - phpcs
  - test

script:
  - make tests

jobs:
  include:
    - stage: phpcs
      script: make phpcs
